// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: 4INCH_NEW

#ifndef _4INCH_NEW_UI_H
#define _4INCH_NEW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_clockpage_png);    // assets/Clockpage.png
LV_IMG_DECLARE(ui_img_circle_7_png);    // assets/circle 7.png
LV_IMG_DECLARE(ui_img_circle1_png);    // assets/circle1.png
LV_IMG_DECLARE(ui_img_1907357479);    // assets/hula-hoop1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets/particle_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets/particle_3.png
LV_IMG_DECLARE(ui_img_1757784814);    // assets/PROFILE-SOLUTION-LOGO-1.png
LV_IMG_DECLARE(ui_img_square1_png);    // assets/square1.png
LV_IMG_DECLARE(ui_img_545167323);    // assets/Transmonk-600x275.png
LV_IMG_DECLARE(ui_img_1116411096);    // assets/two-arrow1.png
LV_IMG_DECLARE(ui_img_uqoxj1_png);    // assets/uqOXJ1.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets/water_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets/water_2.png


LV_FONT_DECLARE(ui_font_cr10);
LV_FONT_DECLARE(ui_font_cr12);
LV_FONT_DECLARE(ui_font_cr14);
LV_FONT_DECLARE(ui_font_cr16);
LV_FONT_DECLARE(ui_font_cr20);
LV_FONT_DECLARE(ui_font_cr40);
LV_FONT_DECLARE(ui_font_cr72);
LV_FONT_DECLARE(ui_font_cr84);
LV_FONT_DECLARE(ui_font_crb20);
LV_FONT_DECLARE(ui_font_crb32);
LV_FONT_DECLARE(ui_font_crb84);
LV_FONT_DECLARE(ui_font_DIGIT);
LV_FONT_DECLARE(ui_font_DIGIT42);
LV_FONT_DECLARE(ui_font_Digit72);
LV_FONT_DECLARE(ui_font_Display16);
LV_FONT_DECLARE(ui_font_Display24);
LV_FONT_DECLARE(ui_font_disp_50);
LV_FONT_DECLARE(ui_font_disp_55);
LV_FONT_DECLARE(ui_font_disp_60);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font24);
LV_FONT_DECLARE(ui_font_Font48);
LV_FONT_DECLARE(ui_font_Font64);
LV_FONT_DECLARE(ui_font_RB10);
LV_FONT_DECLARE(ui_font_RB12);
LV_FONT_DECLARE(ui_font_RB14);
LV_FONT_DECLARE(ui_font_RB18);
LV_FONT_DECLARE(ui_font_RB20);
LV_FONT_DECLARE(ui_font_RB24);
LV_FONT_DECLARE(ui_font_RB26);
LV_FONT_DECLARE(ui_font_RB32);
LV_FONT_DECLARE(ui_font_RB50);
LV_FONT_DECLARE(ui_font_RB60);
LV_FONT_DECLARE(ui_font_RB72);
LV_FONT_DECLARE(ui_font_RB8);
LV_FONT_DECLARE(ui_font_ROBOTO12);
LV_FONT_DECLARE(ui_font_Roboto16);
LV_FONT_DECLARE(ui_font_roboto24);
LV_FONT_DECLARE(ui_font_roboto32);
LV_FONT_DECLARE(ui_font_Roboto40);
LV_FONT_DECLARE(ui_font_Roboto44);
LV_FONT_DECLARE(ui_font_Robotonum72);
LV_FONT_DECLARE(ui_font_RR12);
LV_FONT_DECLARE(ui_font_RR14);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
